
          "suggestions_url": "https://us.search.yahoo.com/sugg/gossip/gossip-us-partner?outputu003dfxjsonu0026appidu003dmcau0026sourceu003dyahoo_mcafee_searchassistu0026commandu003d{searchTerms}",
      "favicon_url": "https://search.yahoo.com/favicon.ico",
      "safe_for_autoreplace": false,
      "date_created": 13232570689582304,
      "url": "https://search.yahoo.com/search?fru003dmcafeeu0026typeu003dE210US91088G0u0026pu003d{searchTerms}",
      "new_tab_url": "",
      "originating_url": "",
      "sync_guid": "F59B2EC8-1D34-435D-B539-435BA415D1B6",
      "short_name": "Secure Search",
      
      "keyword": "mcafee",
      "input_encodings": "",
      "prepopulate_id": 1001,
      "last_modified": 13232570689582304
